name: Packer Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hcp-packer-ubuntu22-base
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run set vars
        id: vars
        run: |
         echo "" >> packer.auto.pkrvars.hcl
         echo '"az_region          = \"japaneast\"" >> packer.auto.pkrvars.hcl'
         echo '"az_resource_group  = \"packer_tutorial\"" >> packer.auto.pkrvars.hcl'
         echo '"az_image_gallery   = \"packer_tutorial_image_gallery\"" >> packer.auto.pkrvars.hcl'
         echo '"az_subscription_id = \"${{ secrets.AZURE_SUBSCRIPTION }\" >> packer.auto.pkrvars.hcl'
         echo '"department         = \"GPS JP Tech\""  >> packer.auto.pkrvars.hcl'
         echo '"owner              = \"image.engineer\""  >> packer.auto.pkrvars.hcl'
         echo '"prefix             = \"gpsjptech\""  >> packer.auto.pkrvars.hcl'

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Build Artifact
        if: ${{ !env.ACT }}
        run: packer build -color=true -on-error=abort .
        env:
            HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
            HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
            HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"
